### ISSUE TITLE
Game crashes when beginning to break

### ISSUE THREAD

**Issue by Camawama** [AtomicStryker/atomicstrykers-minecraft-mods#467]
Game crashes when breaking a block. here is the report.

[crash-2023-02-11_23.03.36-client.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/10715359/crash-2023-02-11_23.03.36-client.txt)

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/282aa05223082972344756dd888cd00b5d830f73

I have pushed a concurrency fix into the tick hook, but this should not be happening in the first place. I suspect you have another mod causing this, and will probably run into other issues now...

Multi Mine 1.18.4 is pushed to curse

**Comment by Camawama** [comment]
Thank you, I will give it another test!

**Comment by Camawama** [comment]
It it working fine now!

**Comment by AtomicStryker** [comment]
Good to hear

**Comment by Camawama** [comment]
Alright, I'm back again to report that it's still broken. Appears to only cause a crash while in singleplayer though!

[crash-2023-02-14_10.13.21-client.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/10734563/crash-2023-02-14_10.13.21-client.txt)


[latest.log](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/10734565/latest.log)

**Comment by AtomicStryker** [comment]
Ah, i am a fool, it is not another mod causing this concurrency but myself. MC now does packet handling async, which means i have to synchronize the packets or else this happens ...

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/51e992f345ac221c2b0fc39661a970d393951d9c
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/57eae3791aff058260215f8915de8a603cddd55c

Pushed new versions for 1.18 and 1.19.3 to curse

**Comment by Camawama** [comment]
You have got to be the most efficient dev out there, my issues are never resolved this fast! Thank you :D

**Comment by Camawama** [comment]
Now wait, It's once again not working...why is it random??

**Comment by AtomicStryker** [comment]
Same stack trace?

**Comment by Camawama** [comment]
Sorry, let me send the logs and stuff again. (Also, I've had no issues server-side and the client doesn't even crash on the server).

![image](https://user-images.githubusercontent.com/43620900/219084367-66f95ed2-211d-41e2-abec-504675f4ca2a.png)

[crash-2023-02-15_10.08.10-client.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/10745028/crash-2023-02-15_10.08.10-client.txt)

[latest.log](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/10745032/latest.log)

**Comment by AtomicStryker** [comment]
OK! So i've asked in the forge discord for higher wisdom and got told i am missing a logical side check (client/server), and this may have worked in older Forge versions because of a bug, and doesnt work anymore. This might explain why i never saw your crash in my testing. I have updated the forge versions for 1.18 and 1.19, added the logical side check, tested it in my singleplayer, and pushed new versions to curse
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/6f86ab6295710200628a569ffda2504fc7384eb5
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/bbdb54a8f77ecbfedfb61875a90b1e0bb4648589

**Comment by Camawama** [comment]
I tested it singleplayer and multiplayer and am happy to report that it's all working perfectly! Thank you !!!

**Comment by tzwel** [comment]
any chances this will work in 1.19.2?

**Comment by AtomicStryker** [comment]
1.19.2.3 will certainly do (its the one from march for 1.19.2)
https://legacy.curseforge.com/minecraft/mc-mods/multi-mine/files

**Comment by tzwel** [comment]
i tried it before, but couldn't be bothered enough to find this issue again
it works like a charm, thanks!
